services:
  - type: web
    name: shanghuyun-django-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py createsuperuser --noinput 
    startCommand: gunicorn myproject.wsgi:application